package b4a.diplomna;


import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.BALayout;
import anywheresoftware.b4a.debug.*;

public class jsonserializations {
private static jsonserializations mostCurrent = new jsonserializations();
public static Object getObject() {
    throw new RuntimeException("Code module does not support this method.");
}
 
public anywheresoftware.b4a.keywords.Common __c = null;
public b4a.diplomna.main _main = null;
public b4a.diplomna.uisizes _uisizes = null;
public b4a.diplomna.support _support = null;
public b4a.diplomna.types _types = null;
public b4a.diplomna.appcolors _appcolors = null;
public b4a.diplomna.data _data = null;
public b4a.diplomna.starter _starter = null;
public b4a.diplomna.httputils2service _httputils2service = null;
public static b4a.diplomna.types._customer  _serializelogincustomer(anywheresoftware.b4a.BA _ba,String _jstring) throws Exception{
RDebugUtils.currentModule="jsonserializations";
if (Debug.shouldDelegate(null, "serializelogincustomer", false))
	 {return ((b4a.diplomna.types._customer) Debug.delegate(null, "serializelogincustomer", new Object[] {_ba,_jstring}));}
anywheresoftware.b4a.objects.collections.JSONParser _json = null;
anywheresoftware.b4a.objects.collections.Map _map1 = null;
b4a.diplomna.types._customer _customer = null;
RDebugUtils.currentLine=3604480;
 //BA.debugLineNum = 3604480;BA.debugLine="Public Sub SerializeLoginCustomer(jstring As Strin";
RDebugUtils.currentLine=3604481;
 //BA.debugLineNum = 3604481;BA.debugLine="Dim JSON As JSONParser";
_json = new anywheresoftware.b4a.objects.collections.JSONParser();
RDebugUtils.currentLine=3604482;
 //BA.debugLineNum = 3604482;BA.debugLine="Dim Map1 As Map";
_map1 = new anywheresoftware.b4a.objects.collections.Map();
RDebugUtils.currentLine=3604483;
 //BA.debugLineNum = 3604483;BA.debugLine="Dim customer As Customer";
_customer = new b4a.diplomna.types._customer();
RDebugUtils.currentLine=3604484;
 //BA.debugLineNum = 3604484;BA.debugLine="Map1.Initialize";
_map1.Initialize();
RDebugUtils.currentLine=3604485;
 //BA.debugLineNum = 3604485;BA.debugLine="customer.Initialize";
_customer.Initialize();
RDebugUtils.currentLine=3604487;
 //BA.debugLineNum = 3604487;BA.debugLine="JSON.Initialize(jstring)";
_json.Initialize(_jstring);
RDebugUtils.currentLine=3604488;
 //BA.debugLineNum = 3604488;BA.debugLine="Map1 = JSON.NextObject";
_map1 = _json.NextObject();
RDebugUtils.currentLine=3604490;
 //BA.debugLineNum = 3604490;BA.debugLine="customer.ID =  Map1.Get(\"id\")";
_customer.ID = (int)(BA.ObjectToNumber(_map1.Get((Object)("id"))));
RDebugUtils.currentLine=3604491;
 //BA.debugLineNum = 3604491;BA.debugLine="customer.username =  Map1.Get(\"username\")";
_customer.username = BA.ObjectToString(_map1.Get((Object)("username")));
RDebugUtils.currentLine=3604492;
 //BA.debugLineNum = 3604492;BA.debugLine="customer.password =  Map1.Get(\"password\")";
_customer.password = BA.ObjectToString(_map1.Get((Object)("password")));
RDebugUtils.currentLine=3604493;
 //BA.debugLineNum = 3604493;BA.debugLine="customer.FirstName =  Map1.Get(\"firstName\")";
_customer.FirstName = BA.ObjectToString(_map1.Get((Object)("firstName")));
RDebugUtils.currentLine=3604494;
 //BA.debugLineNum = 3604494;BA.debugLine="customer.LastName =  Map1.Get(\"lastName\")";
_customer.LastName = BA.ObjectToString(_map1.Get((Object)("lastName")));
RDebugUtils.currentLine=3604495;
 //BA.debugLineNum = 3604495;BA.debugLine="customer.email =  Map1.Get(\"email\")";
_customer.email = BA.ObjectToString(_map1.Get((Object)("email")));
RDebugUtils.currentLine=3604496;
 //BA.debugLineNum = 3604496;BA.debugLine="customer.City =  Map1.Get(\"city\")";
_customer.City = BA.ObjectToString(_map1.Get((Object)("city")));
RDebugUtils.currentLine=3604497;
 //BA.debugLineNum = 3604497;BA.debugLine="customer.Phone =  Map1.Get(\"phone\")";
_customer.Phone = BA.ObjectToString(_map1.Get((Object)("phone")));
RDebugUtils.currentLine=3604499;
 //BA.debugLineNum = 3604499;BA.debugLine="Return customer";
if (true) return _customer;
RDebugUtils.currentLine=3604500;
 //BA.debugLineNum = 3604500;BA.debugLine="End Sub";
return null;
}
public static anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator  _customerid(anywheresoftware.b4a.BA _ba,int _id) throws Exception{
RDebugUtils.currentModule="jsonserializations";
if (Debug.shouldDelegate(null, "customerid", false))
	 {return ((anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator) Debug.delegate(null, "customerid", new Object[] {_ba,_id}));}
anywheresoftware.b4a.objects.collections.Map _jsondata = null;
anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator _jsongenerator = null;
RDebugUtils.currentLine=3735552;
 //BA.debugLineNum = 3735552;BA.debugLine="Public Sub CustomerID(ID As Int) As JSONGenerator";
RDebugUtils.currentLine=3735553;
 //BA.debugLineNum = 3735553;BA.debugLine="Dim JsonData As Map";
_jsondata = new anywheresoftware.b4a.objects.collections.Map();
RDebugUtils.currentLine=3735554;
 //BA.debugLineNum = 3735554;BA.debugLine="JsonData.Initialize";
_jsondata.Initialize();
RDebugUtils.currentLine=3735555;
 //BA.debugLineNum = 3735555;BA.debugLine="JsonData.Put(\"id\", ID)";
_jsondata.Put((Object)("id"),(Object)(_id));
RDebugUtils.currentLine=3735557;
 //BA.debugLineNum = 3735557;BA.debugLine="Dim JSONGenerator As JSONGenerator";
_jsongenerator = new anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator();
RDebugUtils.currentLine=3735558;
 //BA.debugLineNum = 3735558;BA.debugLine="JSONGenerator.Initialize(JsonData)";
_jsongenerator.Initialize(_jsondata);
RDebugUtils.currentLine=3735559;
 //BA.debugLineNum = 3735559;BA.debugLine="Log(JSONGenerator.ToPrettyString(0))";
anywheresoftware.b4a.keywords.Common.LogImpl("43735559",_jsongenerator.ToPrettyString((int) (0)),0);
RDebugUtils.currentLine=3735560;
 //BA.debugLineNum = 3735560;BA.debugLine="Return JSONGenerator";
if (true) return _jsongenerator;
RDebugUtils.currentLine=3735561;
 //BA.debugLineNum = 3735561;BA.debugLine="End Sub";
return null;
}
public static anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator  _loginjson(anywheresoftware.b4a.BA _ba,String _username,String _password) throws Exception{
RDebugUtils.currentModule="jsonserializations";
if (Debug.shouldDelegate(null, "loginjson", false))
	 {return ((anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator) Debug.delegate(null, "loginjson", new Object[] {_ba,_username,_password}));}
anywheresoftware.b4a.objects.collections.Map _jsondata = null;
anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator _jsongenerator = null;
RDebugUtils.currentLine=3670016;
 //BA.debugLineNum = 3670016;BA.debugLine="Public Sub LoginJson(username As String , password";
RDebugUtils.currentLine=3670017;
 //BA.debugLineNum = 3670017;BA.debugLine="Dim JsonData As Map";
_jsondata = new anywheresoftware.b4a.objects.collections.Map();
RDebugUtils.currentLine=3670018;
 //BA.debugLineNum = 3670018;BA.debugLine="JsonData.Initialize";
_jsondata.Initialize();
RDebugUtils.currentLine=3670019;
 //BA.debugLineNum = 3670019;BA.debugLine="JsonData.Put(\"username\", username)";
_jsondata.Put((Object)("username"),(Object)(_username));
RDebugUtils.currentLine=3670020;
 //BA.debugLineNum = 3670020;BA.debugLine="JsonData.Put(\"password\", password)";
_jsondata.Put((Object)("password"),(Object)(_password));
RDebugUtils.currentLine=3670022;
 //BA.debugLineNum = 3670022;BA.debugLine="Dim JSONGenerator As JSONGenerator";
_jsongenerator = new anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator();
RDebugUtils.currentLine=3670023;
 //BA.debugLineNum = 3670023;BA.debugLine="JSONGenerator.Initialize(JsonData)";
_jsongenerator.Initialize(_jsondata);
RDebugUtils.currentLine=3670024;
 //BA.debugLineNum = 3670024;BA.debugLine="Log(JSONGenerator.ToPrettyString(0))";
anywheresoftware.b4a.keywords.Common.LogImpl("43670024",_jsongenerator.ToPrettyString((int) (0)),0);
RDebugUtils.currentLine=3670025;
 //BA.debugLineNum = 3670025;BA.debugLine="Return JSONGenerator";
if (true) return _jsongenerator;
RDebugUtils.currentLine=3670026;
 //BA.debugLineNum = 3670026;BA.debugLine="End Sub";
return null;
}
public static anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator  _customertojson(anywheresoftware.b4a.BA _ba,b4a.diplomna.types._customer _c) throws Exception{
RDebugUtils.currentModule="jsonserializations";
if (Debug.shouldDelegate(null, "customertojson", false))
	 {return ((anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator) Debug.delegate(null, "customertojson", new Object[] {_ba,_c}));}
anywheresoftware.b4a.objects.collections.Map _jsondata = null;
anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator _jsongenerator = null;
RDebugUtils.currentLine=3866624;
 //BA.debugLineNum = 3866624;BA.debugLine="Public Sub CustomerToJSON(c As Customer)As JSONGen";
RDebugUtils.currentLine=3866625;
 //BA.debugLineNum = 3866625;BA.debugLine="Dim JsonData As Map";
_jsondata = new anywheresoftware.b4a.objects.collections.Map();
RDebugUtils.currentLine=3866626;
 //BA.debugLineNum = 3866626;BA.debugLine="JsonData.Initialize";
_jsondata.Initialize();
RDebugUtils.currentLine=3866627;
 //BA.debugLineNum = 3866627;BA.debugLine="JsonData.Put(\"id\",c.ID)";
_jsondata.Put((Object)("id"),(Object)(_c.ID));
RDebugUtils.currentLine=3866628;
 //BA.debugLineNum = 3866628;BA.debugLine="JsonData.Put(\"username\", c.username)";
_jsondata.Put((Object)("username"),(Object)(_c.username));
RDebugUtils.currentLine=3866629;
 //BA.debugLineNum = 3866629;BA.debugLine="JsonData.Put(\"password\",c.password )";
_jsondata.Put((Object)("password"),(Object)(_c.password));
RDebugUtils.currentLine=3866630;
 //BA.debugLineNum = 3866630;BA.debugLine="JsonData.Put(\"email\",c.email )";
_jsondata.Put((Object)("email"),(Object)(_c.email));
RDebugUtils.currentLine=3866631;
 //BA.debugLineNum = 3866631;BA.debugLine="JsonData.Put(\"firstName\",c.FirstName )";
_jsondata.Put((Object)("firstName"),(Object)(_c.FirstName));
RDebugUtils.currentLine=3866632;
 //BA.debugLineNum = 3866632;BA.debugLine="JsonData.Put(\"lastName\",c.LastName )";
_jsondata.Put((Object)("lastName"),(Object)(_c.LastName));
RDebugUtils.currentLine=3866633;
 //BA.debugLineNum = 3866633;BA.debugLine="JsonData.Put(\"phone\",c.Phone )";
_jsondata.Put((Object)("phone"),(Object)(_c.Phone));
RDebugUtils.currentLine=3866634;
 //BA.debugLineNum = 3866634;BA.debugLine="JsonData.Put(\"city\",c.City )";
_jsondata.Put((Object)("city"),(Object)(_c.City));
RDebugUtils.currentLine=3866635;
 //BA.debugLineNum = 3866635;BA.debugLine="JsonData.Put(\"country\",c.Country )";
_jsondata.Put((Object)("country"),(Object)(_c.Country));
RDebugUtils.currentLine=3866636;
 //BA.debugLineNum = 3866636;BA.debugLine="JsonData.Put(\"address\",c.Address )";
_jsondata.Put((Object)("address"),(Object)(_c.Address));
RDebugUtils.currentLine=3866638;
 //BA.debugLineNum = 3866638;BA.debugLine="Dim JSONGenerator As JSONGenerator";
_jsongenerator = new anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator();
RDebugUtils.currentLine=3866639;
 //BA.debugLineNum = 3866639;BA.debugLine="JSONGenerator.Initialize(JsonData)";
_jsongenerator.Initialize(_jsondata);
RDebugUtils.currentLine=3866640;
 //BA.debugLineNum = 3866640;BA.debugLine="Log(JSONGenerator.ToPrettyString(0))";
anywheresoftware.b4a.keywords.Common.LogImpl("43866640",_jsongenerator.ToPrettyString((int) (0)),0);
RDebugUtils.currentLine=3866641;
 //BA.debugLineNum = 3866641;BA.debugLine="Return JSONGenerator";
if (true) return _jsongenerator;
RDebugUtils.currentLine=3866643;
 //BA.debugLineNum = 3866643;BA.debugLine="End Sub";
return null;
}
public static anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator  _ordertojson(anywheresoftware.b4a.BA _ba,b4a.diplomna.types._order _o) throws Exception{
RDebugUtils.currentModule="jsonserializations";
if (Debug.shouldDelegate(null, "ordertojson", false))
	 {return ((anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator) Debug.delegate(null, "ordertojson", new Object[] {_ba,_o}));}
anywheresoftware.b4a.objects.collections.Map _jsondata = null;
anywheresoftware.b4a.objects.collections.List _jsonarray = null;
b4a.diplomna.types._orderedgood _og = null;
anywheresoftware.b4a.objects.collections.Map _jsondata2 = null;
anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator _jsongenerator = null;
RDebugUtils.currentLine=3801088;
 //BA.debugLineNum = 3801088;BA.debugLine="Public Sub OrderToJSON(o As Order) As JSONGenerato";
RDebugUtils.currentLine=3801089;
 //BA.debugLineNum = 3801089;BA.debugLine="Dim JsonData As Map";
_jsondata = new anywheresoftware.b4a.objects.collections.Map();
RDebugUtils.currentLine=3801090;
 //BA.debugLineNum = 3801090;BA.debugLine="Dim JsonArray As List";
_jsonarray = new anywheresoftware.b4a.objects.collections.List();
RDebugUtils.currentLine=3801091;
 //BA.debugLineNum = 3801091;BA.debugLine="JsonData.Initialize";
_jsondata.Initialize();
RDebugUtils.currentLine=3801092;
 //BA.debugLineNum = 3801092;BA.debugLine="JsonArray.Initialize";
_jsonarray.Initialize();
RDebugUtils.currentLine=3801094;
 //BA.debugLineNum = 3801094;BA.debugLine="JsonData.Put(\"id\",o.ID)";
_jsondata.Put((Object)("id"),(Object)(_o.ID));
RDebugUtils.currentLine=3801095;
 //BA.debugLineNum = 3801095;BA.debugLine="JsonData.Put(\"orderCode\",o.OrderCode)";
_jsondata.Put((Object)("orderCode"),(Object)(_o.OrderCode));
RDebugUtils.currentLine=3801096;
 //BA.debugLineNum = 3801096;BA.debugLine="JsonData.Put(\"customerID\",o.CutomerID)";
_jsondata.Put((Object)("customerID"),(Object)(_o.CutomerID));
RDebugUtils.currentLine=3801097;
 //BA.debugLineNum = 3801097;BA.debugLine="JsonData.Put(\"orderTotalPrice\",o.OrderTotalPrice)";
_jsondata.Put((Object)("orderTotalPrice"),(Object)(_o.OrderTotalPrice));
RDebugUtils.currentLine=3801098;
 //BA.debugLineNum = 3801098;BA.debugLine="JsonData.Put(\"orderStatus\",o.OrderStatus)";
_jsondata.Put((Object)("orderStatus"),(Object)(_o.OrderStatus));
RDebugUtils.currentLine=3801099;
 //BA.debugLineNum = 3801099;BA.debugLine="For Each og As OrderedGood In o.OrderedGoods";
{
final anywheresoftware.b4a.BA.IterableList group10 = _o.OrderedGoods;
final int groupLen10 = group10.getSize()
;int index10 = 0;
;
for (; index10 < groupLen10;index10++){
_og = (b4a.diplomna.types._orderedgood)(group10.Get(index10));
RDebugUtils.currentLine=3801100;
 //BA.debugLineNum = 3801100;BA.debugLine="Dim JsonData2 As Map";
_jsondata2 = new anywheresoftware.b4a.objects.collections.Map();
RDebugUtils.currentLine=3801101;
 //BA.debugLineNum = 3801101;BA.debugLine="JsonData2.Initialize";
_jsondata2.Initialize();
RDebugUtils.currentLine=3801102;
 //BA.debugLineNum = 3801102;BA.debugLine="JsonData2.Put(\"order\",Null)";
_jsondata2.Put((Object)("order"),anywheresoftware.b4a.keywords.Common.Null);
RDebugUtils.currentLine=3801103;
 //BA.debugLineNum = 3801103;BA.debugLine="JsonData2.Put(\"orderID\",og.OrderID)";
_jsondata2.Put((Object)("orderID"),(Object)(_og.OrderID));
RDebugUtils.currentLine=3801104;
 //BA.debugLineNum = 3801104;BA.debugLine="JsonData2.Put(\"goodID\",og.GoodID)";
_jsondata2.Put((Object)("goodID"),(Object)(_og.GoodID));
RDebugUtils.currentLine=3801105;
 //BA.debugLineNum = 3801105;BA.debugLine="JsonData2.Put(\"qtty\",og.Qtty)";
_jsondata2.Put((Object)("qtty"),(Object)(_og.Qtty));
RDebugUtils.currentLine=3801106;
 //BA.debugLineNum = 3801106;BA.debugLine="JsonArray.Add(JsonData2)";
_jsonarray.Add((Object)(_jsondata2.getObject()));
 }
};
RDebugUtils.currentLine=3801108;
 //BA.debugLineNum = 3801108;BA.debugLine="JsonData.Put(\"orderedGoods\",JsonArray)";
_jsondata.Put((Object)("orderedGoods"),(Object)(_jsonarray.getObject()));
RDebugUtils.currentLine=3801110;
 //BA.debugLineNum = 3801110;BA.debugLine="Dim JSONGenerator As JSONGenerator";
_jsongenerator = new anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator();
RDebugUtils.currentLine=3801111;
 //BA.debugLineNum = 3801111;BA.debugLine="JSONGenerator.Initialize(JsonData)";
_jsongenerator.Initialize(_jsondata);
RDebugUtils.currentLine=3801112;
 //BA.debugLineNum = 3801112;BA.debugLine="Log(JSONGenerator.ToPrettyString(0))";
anywheresoftware.b4a.keywords.Common.LogImpl("43801112",_jsongenerator.ToPrettyString((int) (0)),0);
RDebugUtils.currentLine=3801113;
 //BA.debugLineNum = 3801113;BA.debugLine="Return JSONGenerator";
if (true) return _jsongenerator;
RDebugUtils.currentLine=3801114;
 //BA.debugLineNum = 3801114;BA.debugLine="End Sub";
return null;
}
public static anywheresoftware.b4a.objects.collections.List  _serializecustomerorders(anywheresoftware.b4a.BA _ba,String _jstring) throws Exception{
RDebugUtils.currentModule="jsonserializations";
if (Debug.shouldDelegate(null, "serializecustomerorders", false))
	 {return ((anywheresoftware.b4a.objects.collections.List) Debug.delegate(null, "serializecustomerorders", new Object[] {_ba,_jstring}));}
anywheresoftware.b4a.objects.collections.JSONParser _json = null;
anywheresoftware.b4a.objects.collections.List _list1 = null;
anywheresoftware.b4a.objects.collections.List _result = null;
int _i = 0;
b4a.diplomna.types._order _ordertmp = null;
anywheresoftware.b4a.objects.collections.Map _map1 = null;
anywheresoftware.b4a.objects.collections.List _orderedgoods = null;
RDebugUtils.currentLine=3932160;
 //BA.debugLineNum = 3932160;BA.debugLine="Public Sub SerializeCustomerOrders(jstring As Stri";
RDebugUtils.currentLine=3932161;
 //BA.debugLineNum = 3932161;BA.debugLine="Dim JSON As JSONParser";
_json = new anywheresoftware.b4a.objects.collections.JSONParser();
RDebugUtils.currentLine=3932162;
 //BA.debugLineNum = 3932162;BA.debugLine="Dim list1 As List";
_list1 = new anywheresoftware.b4a.objects.collections.List();
RDebugUtils.currentLine=3932163;
 //BA.debugLineNum = 3932163;BA.debugLine="Dim result As List";
_result = new anywheresoftware.b4a.objects.collections.List();
RDebugUtils.currentLine=3932165;
 //BA.debugLineNum = 3932165;BA.debugLine="result.Initialize";
_result.Initialize();
RDebugUtils.currentLine=3932166;
 //BA.debugLineNum = 3932166;BA.debugLine="JSON.Initialize(jstring)";
_json.Initialize(_jstring);
RDebugUtils.currentLine=3932167;
 //BA.debugLineNum = 3932167;BA.debugLine="list1 = JSON.NextArray";
_list1 = _json.NextArray();
RDebugUtils.currentLine=3932169;
 //BA.debugLineNum = 3932169;BA.debugLine="For i = 0 To list1.Size - 1";
{
final int step7 = 1;
final int limit7 = (int) (_list1.getSize()-1);
_i = (int) (0) ;
for (;_i <= limit7 ;_i = _i + step7 ) {
RDebugUtils.currentLine=3932170;
 //BA.debugLineNum = 3932170;BA.debugLine="Dim Ordertmp As Order";
_ordertmp = new b4a.diplomna.types._order();
RDebugUtils.currentLine=3932171;
 //BA.debugLineNum = 3932171;BA.debugLine="Dim Map1 As Map";
_map1 = new anywheresoftware.b4a.objects.collections.Map();
RDebugUtils.currentLine=3932172;
 //BA.debugLineNum = 3932172;BA.debugLine="Dim OrderedGoods As List";
_orderedgoods = new anywheresoftware.b4a.objects.collections.List();
RDebugUtils.currentLine=3932174;
 //BA.debugLineNum = 3932174;BA.debugLine="Map1 = list1.Get(i)";
_map1.setObject((anywheresoftware.b4a.objects.collections.Map.MyMap)(_list1.Get(_i)));
RDebugUtils.currentLine=3932175;
 //BA.debugLineNum = 3932175;BA.debugLine="Ordertmp.Initialize";
_ordertmp.Initialize();
RDebugUtils.currentLine=3932176;
 //BA.debugLineNum = 3932176;BA.debugLine="Ordertmp.ID = Map1.Get(\"id\")";
_ordertmp.ID = (int)(BA.ObjectToNumber(_map1.Get((Object)("id"))));
RDebugUtils.currentLine=3932177;
 //BA.debugLineNum = 3932177;BA.debugLine="Ordertmp.OrderCode = Map1.Get(\"orderCode\")";
_ordertmp.OrderCode = BA.ObjectToString(_map1.Get((Object)("orderCode")));
RDebugUtils.currentLine=3932178;
 //BA.debugLineNum = 3932178;BA.debugLine="Ordertmp.CutomerID = Map1.Get(\"customerID\")";
_ordertmp.CutomerID = (int)(BA.ObjectToNumber(_map1.Get((Object)("customerID"))));
RDebugUtils.currentLine=3932179;
 //BA.debugLineNum = 3932179;BA.debugLine="Ordertmp.OrderTotalPrice = Map1.Get(\"orderTotalP";
_ordertmp.OrderTotalPrice = (double)(BA.ObjectToNumber(_map1.Get((Object)("orderTotalPrice"))));
RDebugUtils.currentLine=3932180;
 //BA.debugLineNum = 3932180;BA.debugLine="Ordertmp.OrderStatus = Map1.Get(\"orderStatus\")";
_ordertmp.OrderStatus = BA.ObjectToString(_map1.Get((Object)("orderStatus")));
RDebugUtils.currentLine=3932181;
 //BA.debugLineNum = 3932181;BA.debugLine="OrderedGoods = Map1.Get(\"orderedGoods\")";
_orderedgoods.setObject((java.util.List)(_map1.Get((Object)("orderedGoods"))));
RDebugUtils.currentLine=3932182;
 //BA.debugLineNum = 3932182;BA.debugLine="Ordertmp.OrderedGoods = OrderedGoods";
_ordertmp.OrderedGoods = _orderedgoods;
RDebugUtils.currentLine=3932183;
 //BA.debugLineNum = 3932183;BA.debugLine="result.Add(Ordertmp)";
_result.Add((Object)(_ordertmp));
 }
};
RDebugUtils.currentLine=3932186;
 //BA.debugLineNum = 3932186;BA.debugLine="Return result";
if (true) return _result;
RDebugUtils.currentLine=3932188;
 //BA.debugLineNum = 3932188;BA.debugLine="End Sub";
return null;
}
public static b4a.diplomna.types._good  _serializegood(anywheresoftware.b4a.BA _ba,String _jstring) throws Exception{
RDebugUtils.currentModule="jsonserializations";
if (Debug.shouldDelegate(null, "serializegood", false))
	 {return ((b4a.diplomna.types._good) Debug.delegate(null, "serializegood", new Object[] {_ba,_jstring}));}
anywheresoftware.b4a.objects.collections.JSONParser _json = null;
anywheresoftware.b4a.objects.collections.Map _map1 = null;
b4a.diplomna.types._good _good = null;
RDebugUtils.currentLine=3473408;
 //BA.debugLineNum = 3473408;BA.debugLine="Public Sub SerializeGood(jstring As String) As Goo";
RDebugUtils.currentLine=3473409;
 //BA.debugLineNum = 3473409;BA.debugLine="Dim JSON As JSONParser";
_json = new anywheresoftware.b4a.objects.collections.JSONParser();
RDebugUtils.currentLine=3473410;
 //BA.debugLineNum = 3473410;BA.debugLine="Dim Map1 As Map";
_map1 = new anywheresoftware.b4a.objects.collections.Map();
RDebugUtils.currentLine=3473411;
 //BA.debugLineNum = 3473411;BA.debugLine="Dim good As Good";
_good = new b4a.diplomna.types._good();
RDebugUtils.currentLine=3473412;
 //BA.debugLineNum = 3473412;BA.debugLine="Map1.Initialize";
_map1.Initialize();
RDebugUtils.currentLine=3473413;
 //BA.debugLineNum = 3473413;BA.debugLine="good.Initialize";
_good.Initialize();
RDebugUtils.currentLine=3473415;
 //BA.debugLineNum = 3473415;BA.debugLine="JSON.Initialize(jstring)";
_json.Initialize(_jstring);
RDebugUtils.currentLine=3473416;
 //BA.debugLineNum = 3473416;BA.debugLine="Map1 = JSON.NextObject";
_map1 = _json.NextObject();
RDebugUtils.currentLine=3473418;
 //BA.debugLineNum = 3473418;BA.debugLine="good.ID = Map1.Get(\"id\")";
_good.ID = (int)(BA.ObjectToNumber(_map1.Get((Object)("id"))));
RDebugUtils.currentLine=3473419;
 //BA.debugLineNum = 3473419;BA.debugLine="good.PLU = Map1.Get(\"plu\")";
_good.PLU = (int)(BA.ObjectToNumber(_map1.Get((Object)("plu"))));
RDebugUtils.currentLine=3473420;
 //BA.debugLineNum = 3473420;BA.debugLine="good.Name = Map1.Get(\"name\")";
_good.Name = BA.ObjectToString(_map1.Get((Object)("name")));
RDebugUtils.currentLine=3473421;
 //BA.debugLineNum = 3473421;BA.debugLine="good.Price = Map1.Get(\"price\")";
_good.Price = (double)(BA.ObjectToNumber(_map1.Get((Object)("price"))));
RDebugUtils.currentLine=3473422;
 //BA.debugLineNum = 3473422;BA.debugLine="good.Description = Map1.Get(\"description\")";
_good.Description = BA.ObjectToString(_map1.Get((Object)("description")));
RDebugUtils.currentLine=3473423;
 //BA.debugLineNum = 3473423;BA.debugLine="good.Is_Discontinued = Map1.Get(\"is_Discontinued\"";
_good.Is_Discontinued = (int)(BA.ObjectToNumber(_map1.Get((Object)("is_Discontinued"))));
RDebugUtils.currentLine=3473424;
 //BA.debugLineNum = 3473424;BA.debugLine="good.SupplierID = Map1.Get(\"supplierID\")";
_good.SupplierID = (int)(BA.ObjectToNumber(_map1.Get((Object)("supplierID"))));
RDebugUtils.currentLine=3473426;
 //BA.debugLineNum = 3473426;BA.debugLine="Return good";
if (true) return _good;
RDebugUtils.currentLine=3473427;
 //BA.debugLineNum = 3473427;BA.debugLine="End Sub";
return null;
}
public static anywheresoftware.b4a.objects.collections.List  _serializeorderedgoods(anywheresoftware.b4a.BA _ba,String _jstring) throws Exception{
RDebugUtils.currentModule="jsonserializations";
if (Debug.shouldDelegate(null, "serializeorderedgoods", false))
	 {return ((anywheresoftware.b4a.objects.collections.List) Debug.delegate(null, "serializeorderedgoods", new Object[] {_ba,_jstring}));}
anywheresoftware.b4a.objects.collections.JSONParser _json = null;
anywheresoftware.b4a.objects.collections.List _list1 = null;
anywheresoftware.b4a.objects.collections.List _result = null;
int _i = 0;
b4a.diplomna.types._orderedgood _orderedgood = null;
anywheresoftware.b4a.objects.collections.Map _map1 = null;
RDebugUtils.currentLine=3997696;
 //BA.debugLineNum = 3997696;BA.debugLine="Public Sub SerializeOrderedGoods(jstring As String";
RDebugUtils.currentLine=3997697;
 //BA.debugLineNum = 3997697;BA.debugLine="Dim JSON As JSONParser";
_json = new anywheresoftware.b4a.objects.collections.JSONParser();
RDebugUtils.currentLine=3997698;
 //BA.debugLineNum = 3997698;BA.debugLine="Dim list1 As List";
_list1 = new anywheresoftware.b4a.objects.collections.List();
RDebugUtils.currentLine=3997699;
 //BA.debugLineNum = 3997699;BA.debugLine="Dim result As List";
_result = new anywheresoftware.b4a.objects.collections.List();
RDebugUtils.currentLine=3997701;
 //BA.debugLineNum = 3997701;BA.debugLine="result.Initialize";
_result.Initialize();
RDebugUtils.currentLine=3997702;
 //BA.debugLineNum = 3997702;BA.debugLine="JSON.Initialize(jstring)";
_json.Initialize(_jstring);
RDebugUtils.currentLine=3997703;
 //BA.debugLineNum = 3997703;BA.debugLine="list1 = JSON.NextArray";
_list1 = _json.NextArray();
RDebugUtils.currentLine=3997705;
 //BA.debugLineNum = 3997705;BA.debugLine="For i = 0 To list1.Size - 1";
{
final int step7 = 1;
final int limit7 = (int) (_list1.getSize()-1);
_i = (int) (0) ;
for (;_i <= limit7 ;_i = _i + step7 ) {
RDebugUtils.currentLine=3997706;
 //BA.debugLineNum = 3997706;BA.debugLine="Dim OrderedGood As OrderedGood";
_orderedgood = new b4a.diplomna.types._orderedgood();
RDebugUtils.currentLine=3997707;
 //BA.debugLineNum = 3997707;BA.debugLine="Dim Map1 As Map";
_map1 = new anywheresoftware.b4a.objects.collections.Map();
RDebugUtils.currentLine=3997708;
 //BA.debugLineNum = 3997708;BA.debugLine="OrderedGood.Initialize";
_orderedgood.Initialize();
RDebugUtils.currentLine=3997710;
 //BA.debugLineNum = 3997710;BA.debugLine="Map1 = list1.Get(i)";
_map1.setObject((anywheresoftware.b4a.objects.collections.Map.MyMap)(_list1.Get(_i)));
RDebugUtils.currentLine=3997712;
 //BA.debugLineNum = 3997712;BA.debugLine="OrderedGood.OrderID = Map1.Get(\"orderID\")";
_orderedgood.OrderID = (int)(BA.ObjectToNumber(_map1.Get((Object)("orderID"))));
RDebugUtils.currentLine=3997713;
 //BA.debugLineNum = 3997713;BA.debugLine="OrderedGood.GoodID = Map1.Get(\"goodID\")";
_orderedgood.GoodID = (int)(BA.ObjectToNumber(_map1.Get((Object)("goodID"))));
RDebugUtils.currentLine=3997714;
 //BA.debugLineNum = 3997714;BA.debugLine="OrderedGood.Order = Null";
_orderedgood.Order = (b4a.diplomna.types._order)(anywheresoftware.b4a.keywords.Common.Null);
RDebugUtils.currentLine=3997715;
 //BA.debugLineNum = 3997715;BA.debugLine="OrderedGood.Qtty = Map1.Get(\"qtty\")";
_orderedgood.Qtty = (int)(BA.ObjectToNumber(_map1.Get((Object)("qtty"))));
RDebugUtils.currentLine=3997717;
 //BA.debugLineNum = 3997717;BA.debugLine="result.Add(OrderedGood)";
_result.Add((Object)(_orderedgood));
 }
};
RDebugUtils.currentLine=3997720;
 //BA.debugLineNum = 3997720;BA.debugLine="Return result";
if (true) return _result;
RDebugUtils.currentLine=3997721;
 //BA.debugLineNum = 3997721;BA.debugLine="End Sub";
return null;
}
public static b4a.diplomna.types._supplier  _serializesupplier(anywheresoftware.b4a.BA _ba,String _jstring) throws Exception{
RDebugUtils.currentModule="jsonserializations";
if (Debug.shouldDelegate(null, "serializesupplier", false))
	 {return ((b4a.diplomna.types._supplier) Debug.delegate(null, "serializesupplier", new Object[] {_ba,_jstring}));}
anywheresoftware.b4a.objects.collections.JSONParser _json = null;
anywheresoftware.b4a.objects.collections.Map _map1 = null;
b4a.diplomna.types._supplier _supplier = null;
RDebugUtils.currentLine=3538944;
 //BA.debugLineNum = 3538944;BA.debugLine="Public Sub SerializeSupplier(jstring As String) As";
RDebugUtils.currentLine=3538945;
 //BA.debugLineNum = 3538945;BA.debugLine="Dim JSON As JSONParser";
_json = new anywheresoftware.b4a.objects.collections.JSONParser();
RDebugUtils.currentLine=3538946;
 //BA.debugLineNum = 3538946;BA.debugLine="Dim Map1 As Map";
_map1 = new anywheresoftware.b4a.objects.collections.Map();
RDebugUtils.currentLine=3538947;
 //BA.debugLineNum = 3538947;BA.debugLine="Dim supplier As Supplier";
_supplier = new b4a.diplomna.types._supplier();
RDebugUtils.currentLine=3538948;
 //BA.debugLineNum = 3538948;BA.debugLine="Map1.Initialize";
_map1.Initialize();
RDebugUtils.currentLine=3538949;
 //BA.debugLineNum = 3538949;BA.debugLine="supplier.Initialize";
_supplier.Initialize();
RDebugUtils.currentLine=3538951;
 //BA.debugLineNum = 3538951;BA.debugLine="JSON.Initialize(jstring)";
_json.Initialize(_jstring);
RDebugUtils.currentLine=3538952;
 //BA.debugLineNum = 3538952;BA.debugLine="Map1 = JSON.NextObject";
_map1 = _json.NextObject();
RDebugUtils.currentLine=3538954;
 //BA.debugLineNum = 3538954;BA.debugLine="supplier.ID =  Map1.Get(\"id\")";
_supplier.ID = (int)(BA.ObjectToNumber(_map1.Get((Object)("id"))));
RDebugUtils.currentLine=3538955;
 //BA.debugLineNum = 3538955;BA.debugLine="supplier.SupplierName =  Map1.Get(\"supplierName\")";
_supplier.SupplierName = BA.ObjectToString(_map1.Get((Object)("supplierName")));
RDebugUtils.currentLine=3538956;
 //BA.debugLineNum = 3538956;BA.debugLine="supplier.SupploerPhone =  Map1.Get(\"supplierPhone";
_supplier.SupploerPhone = BA.ObjectToString(_map1.Get((Object)("supplierPhone")));
RDebugUtils.currentLine=3538958;
 //BA.debugLineNum = 3538958;BA.debugLine="Return supplier";
if (true) return _supplier;
RDebugUtils.currentLine=3538959;
 //BA.debugLineNum = 3538959;BA.debugLine="End Sub";
return null;
}
}