package b4a.diplomna;


import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.BALayout;
import anywheresoftware.b4a.debug.*;

public class jsonserializations {
private static jsonserializations mostCurrent = new jsonserializations();
public static Object getObject() {
    throw new RuntimeException("Code module does not support this method.");
}
 public anywheresoftware.b4a.keywords.Common __c = null;
public b4a.diplomna.main _main = null;
public b4a.diplomna.uisizes _uisizes = null;
public b4a.diplomna.support _support = null;
public b4a.diplomna.types _types = null;
public b4a.diplomna.appcolors _appcolors = null;
public b4a.diplomna.data _data = null;
public b4a.diplomna.starter _starter = null;
public b4a.diplomna.httputils2service _httputils2service = null;
public static anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator  _customerid(anywheresoftware.b4a.BA _ba,int _id) throws Exception{
anywheresoftware.b4a.objects.collections.Map _jsondata = null;
anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator _jsongenerator = null;
 //BA.debugLineNum = 82;BA.debugLine="Public Sub CustomerID(ID As Int) As JSONGenerator";
 //BA.debugLineNum = 83;BA.debugLine="Dim JsonData As Map";
_jsondata = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 84;BA.debugLine="JsonData.Initialize";
_jsondata.Initialize();
 //BA.debugLineNum = 85;BA.debugLine="JsonData.Put(\"id\", ID)";
_jsondata.Put((Object)("id"),(Object)(_id));
 //BA.debugLineNum = 87;BA.debugLine="Dim JSONGenerator As JSONGenerator";
_jsongenerator = new anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator();
 //BA.debugLineNum = 88;BA.debugLine="JSONGenerator.Initialize(JsonData)";
_jsongenerator.Initialize(_jsondata);
 //BA.debugLineNum = 89;BA.debugLine="Log(JSONGenerator.ToPrettyString(0))";
anywheresoftware.b4a.keywords.Common.LogImpl("43735559",_jsongenerator.ToPrettyString((int) (0)),0);
 //BA.debugLineNum = 90;BA.debugLine="Return JSONGenerator";
if (true) return _jsongenerator;
 //BA.debugLineNum = 91;BA.debugLine="End Sub";
return null;
}
public static anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator  _customertojson(anywheresoftware.b4a.BA _ba,b4a.diplomna.types._customer _c) throws Exception{
anywheresoftware.b4a.objects.collections.Map _jsondata = null;
anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator _jsongenerator = null;
 //BA.debugLineNum = 121;BA.debugLine="Public Sub CustomerToJSON(c As Customer)As JSONGen";
 //BA.debugLineNum = 122;BA.debugLine="Dim JsonData As Map";
_jsondata = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 123;BA.debugLine="JsonData.Initialize";
_jsondata.Initialize();
 //BA.debugLineNum = 124;BA.debugLine="JsonData.Put(\"id\",c.ID)";
_jsondata.Put((Object)("id"),(Object)(_c.ID));
 //BA.debugLineNum = 125;BA.debugLine="JsonData.Put(\"username\", c.username)";
_jsondata.Put((Object)("username"),(Object)(_c.username));
 //BA.debugLineNum = 126;BA.debugLine="JsonData.Put(\"password\",c.password )";
_jsondata.Put((Object)("password"),(Object)(_c.password));
 //BA.debugLineNum = 127;BA.debugLine="JsonData.Put(\"email\",c.email )";
_jsondata.Put((Object)("email"),(Object)(_c.email));
 //BA.debugLineNum = 128;BA.debugLine="JsonData.Put(\"firstName\",c.FirstName )";
_jsondata.Put((Object)("firstName"),(Object)(_c.FirstName));
 //BA.debugLineNum = 129;BA.debugLine="JsonData.Put(\"lastName\",c.LastName )";
_jsondata.Put((Object)("lastName"),(Object)(_c.LastName));
 //BA.debugLineNum = 130;BA.debugLine="JsonData.Put(\"phone\",c.Phone )";
_jsondata.Put((Object)("phone"),(Object)(_c.Phone));
 //BA.debugLineNum = 131;BA.debugLine="JsonData.Put(\"city\",c.City )";
_jsondata.Put((Object)("city"),(Object)(_c.City));
 //BA.debugLineNum = 132;BA.debugLine="JsonData.Put(\"country\",c.Country )";
_jsondata.Put((Object)("country"),(Object)(_c.Country));
 //BA.debugLineNum = 133;BA.debugLine="JsonData.Put(\"address\",c.Address )";
_jsondata.Put((Object)("address"),(Object)(_c.Address));
 //BA.debugLineNum = 135;BA.debugLine="Dim JSONGenerator As JSONGenerator";
_jsongenerator = new anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator();
 //BA.debugLineNum = 136;BA.debugLine="JSONGenerator.Initialize(JsonData)";
_jsongenerator.Initialize(_jsondata);
 //BA.debugLineNum = 137;BA.debugLine="Log(JSONGenerator.ToPrettyString(0))";
anywheresoftware.b4a.keywords.Common.LogImpl("43866640",_jsongenerator.ToPrettyString((int) (0)),0);
 //BA.debugLineNum = 138;BA.debugLine="Return JSONGenerator";
if (true) return _jsongenerator;
 //BA.debugLineNum = 140;BA.debugLine="End Sub";
return null;
}
public static anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator  _loginjson(anywheresoftware.b4a.BA _ba,String _username,String _password) throws Exception{
anywheresoftware.b4a.objects.collections.Map _jsondata = null;
anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator _jsongenerator = null;
 //BA.debugLineNum = 70;BA.debugLine="Public Sub LoginJson(username As String , password";
 //BA.debugLineNum = 71;BA.debugLine="Dim JsonData As Map";
_jsondata = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 72;BA.debugLine="JsonData.Initialize";
_jsondata.Initialize();
 //BA.debugLineNum = 73;BA.debugLine="JsonData.Put(\"username\", username)";
_jsondata.Put((Object)("username"),(Object)(_username));
 //BA.debugLineNum = 74;BA.debugLine="JsonData.Put(\"password\", password)";
_jsondata.Put((Object)("password"),(Object)(_password));
 //BA.debugLineNum = 76;BA.debugLine="Dim JSONGenerator As JSONGenerator";
_jsongenerator = new anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator();
 //BA.debugLineNum = 77;BA.debugLine="JSONGenerator.Initialize(JsonData)";
_jsongenerator.Initialize(_jsondata);
 //BA.debugLineNum = 78;BA.debugLine="Log(JSONGenerator.ToPrettyString(0))";
anywheresoftware.b4a.keywords.Common.LogImpl("43670024",_jsongenerator.ToPrettyString((int) (0)),0);
 //BA.debugLineNum = 79;BA.debugLine="Return JSONGenerator";
if (true) return _jsongenerator;
 //BA.debugLineNum = 80;BA.debugLine="End Sub";
return null;
}
public static anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator  _ordertojson(anywheresoftware.b4a.BA _ba,b4a.diplomna.types._order _o) throws Exception{
anywheresoftware.b4a.objects.collections.Map _jsondata = null;
anywheresoftware.b4a.objects.collections.List _jsonarray = null;
b4a.diplomna.types._orderedgood _og = null;
anywheresoftware.b4a.objects.collections.Map _jsondata2 = null;
anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator _jsongenerator = null;
 //BA.debugLineNum = 93;BA.debugLine="Public Sub OrderToJSON(o As Order) As JSONGenerato";
 //BA.debugLineNum = 94;BA.debugLine="Dim JsonData As Map";
_jsondata = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 95;BA.debugLine="Dim JsonArray As List";
_jsonarray = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 96;BA.debugLine="JsonData.Initialize";
_jsondata.Initialize();
 //BA.debugLineNum = 97;BA.debugLine="JsonArray.Initialize";
_jsonarray.Initialize();
 //BA.debugLineNum = 99;BA.debugLine="JsonData.Put(\"id\",o.ID)";
_jsondata.Put((Object)("id"),(Object)(_o.ID));
 //BA.debugLineNum = 100;BA.debugLine="JsonData.Put(\"orderCode\",o.OrderCode)";
_jsondata.Put((Object)("orderCode"),(Object)(_o.OrderCode));
 //BA.debugLineNum = 101;BA.debugLine="JsonData.Put(\"customerID\",o.CutomerID)";
_jsondata.Put((Object)("customerID"),(Object)(_o.CutomerID));
 //BA.debugLineNum = 102;BA.debugLine="JsonData.Put(\"orderTotalPrice\",o.OrderTotalPrice)";
_jsondata.Put((Object)("orderTotalPrice"),(Object)(_o.OrderTotalPrice));
 //BA.debugLineNum = 103;BA.debugLine="JsonData.Put(\"orderStatus\",o.OrderStatus)";
_jsondata.Put((Object)("orderStatus"),(Object)(_o.OrderStatus));
 //BA.debugLineNum = 104;BA.debugLine="For Each og As OrderedGood In o.OrderedGoods";
{
final anywheresoftware.b4a.BA.IterableList group10 = _o.OrderedGoods;
final int groupLen10 = group10.getSize()
;int index10 = 0;
;
for (; index10 < groupLen10;index10++){
_og = (b4a.diplomna.types._orderedgood)(group10.Get(index10));
 //BA.debugLineNum = 105;BA.debugLine="Dim JsonData2 As Map";
_jsondata2 = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 106;BA.debugLine="JsonData2.Initialize";
_jsondata2.Initialize();
 //BA.debugLineNum = 107;BA.debugLine="JsonData2.Put(\"order\",Null)";
_jsondata2.Put((Object)("order"),anywheresoftware.b4a.keywords.Common.Null);
 //BA.debugLineNum = 108;BA.debugLine="JsonData2.Put(\"orderID\",og.OrderID)";
_jsondata2.Put((Object)("orderID"),(Object)(_og.OrderID));
 //BA.debugLineNum = 109;BA.debugLine="JsonData2.Put(\"goodID\",og.GoodID)";
_jsondata2.Put((Object)("goodID"),(Object)(_og.GoodID));
 //BA.debugLineNum = 110;BA.debugLine="JsonData2.Put(\"qtty\",og.Qtty)";
_jsondata2.Put((Object)("qtty"),(Object)(_og.Qtty));
 //BA.debugLineNum = 111;BA.debugLine="JsonArray.Add(JsonData2)";
_jsonarray.Add((Object)(_jsondata2.getObject()));
 }
};
 //BA.debugLineNum = 113;BA.debugLine="JsonData.Put(\"orderedGoods\",JsonArray)";
_jsondata.Put((Object)("orderedGoods"),(Object)(_jsonarray.getObject()));
 //BA.debugLineNum = 115;BA.debugLine="Dim JSONGenerator As JSONGenerator";
_jsongenerator = new anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator();
 //BA.debugLineNum = 116;BA.debugLine="JSONGenerator.Initialize(JsonData)";
_jsongenerator.Initialize(_jsondata);
 //BA.debugLineNum = 117;BA.debugLine="Log(JSONGenerator.ToPrettyString(0))";
anywheresoftware.b4a.keywords.Common.LogImpl("43801112",_jsongenerator.ToPrettyString((int) (0)),0);
 //BA.debugLineNum = 118;BA.debugLine="Return JSONGenerator";
if (true) return _jsongenerator;
 //BA.debugLineNum = 119;BA.debugLine="End Sub";
return null;
}
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 3;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 7;BA.debugLine="End Sub";
return "";
}
public static anywheresoftware.b4a.objects.collections.List  _serializecustomerorders(anywheresoftware.b4a.BA _ba,String _jstring) throws Exception{
anywheresoftware.b4a.objects.collections.JSONParser _json = null;
anywheresoftware.b4a.objects.collections.List _list1 = null;
anywheresoftware.b4a.objects.collections.List _result = null;
int _i = 0;
b4a.diplomna.types._order _ordertmp = null;
anywheresoftware.b4a.objects.collections.Map _map1 = null;
anywheresoftware.b4a.objects.collections.List _orderedgoods = null;
 //BA.debugLineNum = 142;BA.debugLine="Public Sub SerializeCustomerOrders(jstring As Stri";
 //BA.debugLineNum = 143;BA.debugLine="Dim JSON As JSONParser";
_json = new anywheresoftware.b4a.objects.collections.JSONParser();
 //BA.debugLineNum = 144;BA.debugLine="Dim list1 As List";
_list1 = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 145;BA.debugLine="Dim result As List";
_result = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 147;BA.debugLine="result.Initialize";
_result.Initialize();
 //BA.debugLineNum = 148;BA.debugLine="JSON.Initialize(jstring)";
_json.Initialize(_jstring);
 //BA.debugLineNum = 149;BA.debugLine="list1 = JSON.NextArray";
_list1 = _json.NextArray();
 //BA.debugLineNum = 151;BA.debugLine="For i = 0 To list1.Size - 1";
{
final int step7 = 1;
final int limit7 = (int) (_list1.getSize()-1);
_i = (int) (0) ;
for (;_i <= limit7 ;_i = _i + step7 ) {
 //BA.debugLineNum = 152;BA.debugLine="Dim Ordertmp As Order";
_ordertmp = new b4a.diplomna.types._order();
 //BA.debugLineNum = 153;BA.debugLine="Dim Map1 As Map";
_map1 = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 154;BA.debugLine="Dim OrderedGoods As List";
_orderedgoods = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 156;BA.debugLine="Map1 = list1.Get(i)";
_map1.setObject((anywheresoftware.b4a.objects.collections.Map.MyMap)(_list1.Get(_i)));
 //BA.debugLineNum = 157;BA.debugLine="Ordertmp.Initialize";
_ordertmp.Initialize();
 //BA.debugLineNum = 158;BA.debugLine="Ordertmp.ID = Map1.Get(\"id\")";
_ordertmp.ID = (int)(BA.ObjectToNumber(_map1.Get((Object)("id"))));
 //BA.debugLineNum = 159;BA.debugLine="Ordertmp.OrderCode = Map1.Get(\"orderCode\")";
_ordertmp.OrderCode = BA.ObjectToString(_map1.Get((Object)("orderCode")));
 //BA.debugLineNum = 160;BA.debugLine="Ordertmp.CutomerID = Map1.Get(\"customerID\")";
_ordertmp.CutomerID = (int)(BA.ObjectToNumber(_map1.Get((Object)("customerID"))));
 //BA.debugLineNum = 161;BA.debugLine="Ordertmp.OrderTotalPrice = Map1.Get(\"orderTotalP";
_ordertmp.OrderTotalPrice = (double)(BA.ObjectToNumber(_map1.Get((Object)("orderTotalPrice"))));
 //BA.debugLineNum = 162;BA.debugLine="Ordertmp.OrderStatus = Map1.Get(\"orderStatus\")";
_ordertmp.OrderStatus = BA.ObjectToString(_map1.Get((Object)("orderStatus")));
 //BA.debugLineNum = 163;BA.debugLine="OrderedGoods = Map1.Get(\"orderedGoods\")";
_orderedgoods.setObject((java.util.List)(_map1.Get((Object)("orderedGoods"))));
 //BA.debugLineNum = 164;BA.debugLine="Ordertmp.OrderedGoods = OrderedGoods";
_ordertmp.OrderedGoods = _orderedgoods;
 //BA.debugLineNum = 165;BA.debugLine="result.Add(Ordertmp)";
_result.Add((Object)(_ordertmp));
 }
};
 //BA.debugLineNum = 168;BA.debugLine="Return result";
if (true) return _result;
 //BA.debugLineNum = 170;BA.debugLine="End Sub";
return null;
}
public static b4a.diplomna.types._good  _serializegood(anywheresoftware.b4a.BA _ba,String _jstring) throws Exception{
anywheresoftware.b4a.objects.collections.JSONParser _json = null;
anywheresoftware.b4a.objects.collections.Map _map1 = null;
b4a.diplomna.types._good _good = null;
 //BA.debugLineNum = 10;BA.debugLine="Public Sub SerializeGood(jstring As String) As Goo";
 //BA.debugLineNum = 11;BA.debugLine="Dim JSON As JSONParser";
_json = new anywheresoftware.b4a.objects.collections.JSONParser();
 //BA.debugLineNum = 12;BA.debugLine="Dim Map1 As Map";
_map1 = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 13;BA.debugLine="Dim good As Good";
_good = new b4a.diplomna.types._good();
 //BA.debugLineNum = 14;BA.debugLine="Map1.Initialize";
_map1.Initialize();
 //BA.debugLineNum = 15;BA.debugLine="good.Initialize";
_good.Initialize();
 //BA.debugLineNum = 17;BA.debugLine="JSON.Initialize(jstring)";
_json.Initialize(_jstring);
 //BA.debugLineNum = 18;BA.debugLine="Map1 = JSON.NextObject";
_map1 = _json.NextObject();
 //BA.debugLineNum = 20;BA.debugLine="good.ID = Map1.Get(\"id\")";
_good.ID = (int)(BA.ObjectToNumber(_map1.Get((Object)("id"))));
 //BA.debugLineNum = 21;BA.debugLine="good.PLU = Map1.Get(\"plu\")";
_good.PLU = (int)(BA.ObjectToNumber(_map1.Get((Object)("plu"))));
 //BA.debugLineNum = 22;BA.debugLine="good.Name = Map1.Get(\"name\")";
_good.Name = BA.ObjectToString(_map1.Get((Object)("name")));
 //BA.debugLineNum = 23;BA.debugLine="good.Price = Map1.Get(\"price\")";
_good.Price = (double)(BA.ObjectToNumber(_map1.Get((Object)("price"))));
 //BA.debugLineNum = 24;BA.debugLine="good.Description = Map1.Get(\"description\")";
_good.Description = BA.ObjectToString(_map1.Get((Object)("description")));
 //BA.debugLineNum = 25;BA.debugLine="good.Is_Discontinued = Map1.Get(\"is_Discontinued\"";
_good.Is_Discontinued = (int)(BA.ObjectToNumber(_map1.Get((Object)("is_Discontinued"))));
 //BA.debugLineNum = 26;BA.debugLine="good.SupplierID = Map1.Get(\"supplierID\")";
_good.SupplierID = (int)(BA.ObjectToNumber(_map1.Get((Object)("supplierID"))));
 //BA.debugLineNum = 28;BA.debugLine="Return good";
if (true) return _good;
 //BA.debugLineNum = 29;BA.debugLine="End Sub";
return null;
}
public static b4a.diplomna.types._customer  _serializelogincustomer(anywheresoftware.b4a.BA _ba,String _jstring) throws Exception{
anywheresoftware.b4a.objects.collections.JSONParser _json = null;
anywheresoftware.b4a.objects.collections.Map _map1 = null;
b4a.diplomna.types._customer _customer = null;
 //BA.debugLineNum = 48;BA.debugLine="Public Sub SerializeLoginCustomer(jstring As Strin";
 //BA.debugLineNum = 49;BA.debugLine="Dim JSON As JSONParser";
_json = new anywheresoftware.b4a.objects.collections.JSONParser();
 //BA.debugLineNum = 50;BA.debugLine="Dim Map1 As Map";
_map1 = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 51;BA.debugLine="Dim customer As Customer";
_customer = new b4a.diplomna.types._customer();
 //BA.debugLineNum = 52;BA.debugLine="Map1.Initialize";
_map1.Initialize();
 //BA.debugLineNum = 53;BA.debugLine="customer.Initialize";
_customer.Initialize();
 //BA.debugLineNum = 55;BA.debugLine="JSON.Initialize(jstring)";
_json.Initialize(_jstring);
 //BA.debugLineNum = 56;BA.debugLine="Map1 = JSON.NextObject";
_map1 = _json.NextObject();
 //BA.debugLineNum = 58;BA.debugLine="customer.ID =  Map1.Get(\"id\")";
_customer.ID = (int)(BA.ObjectToNumber(_map1.Get((Object)("id"))));
 //BA.debugLineNum = 59;BA.debugLine="customer.username =  Map1.Get(\"username\")";
_customer.username = BA.ObjectToString(_map1.Get((Object)("username")));
 //BA.debugLineNum = 60;BA.debugLine="customer.password =  Map1.Get(\"password\")";
_customer.password = BA.ObjectToString(_map1.Get((Object)("password")));
 //BA.debugLineNum = 61;BA.debugLine="customer.FirstName =  Map1.Get(\"firstName\")";
_customer.FirstName = BA.ObjectToString(_map1.Get((Object)("firstName")));
 //BA.debugLineNum = 62;BA.debugLine="customer.LastName =  Map1.Get(\"lastName\")";
_customer.LastName = BA.ObjectToString(_map1.Get((Object)("lastName")));
 //BA.debugLineNum = 63;BA.debugLine="customer.email =  Map1.Get(\"email\")";
_customer.email = BA.ObjectToString(_map1.Get((Object)("email")));
 //BA.debugLineNum = 64;BA.debugLine="customer.City =  Map1.Get(\"city\")";
_customer.City = BA.ObjectToString(_map1.Get((Object)("city")));
 //BA.debugLineNum = 65;BA.debugLine="customer.Phone =  Map1.Get(\"phone\")";
_customer.Phone = BA.ObjectToString(_map1.Get((Object)("phone")));
 //BA.debugLineNum = 67;BA.debugLine="Return customer";
if (true) return _customer;
 //BA.debugLineNum = 68;BA.debugLine="End Sub";
return null;
}
public static anywheresoftware.b4a.objects.collections.List  _serializeorderedgoods(anywheresoftware.b4a.BA _ba,String _jstring) throws Exception{
anywheresoftware.b4a.objects.collections.JSONParser _json = null;
anywheresoftware.b4a.objects.collections.List _list1 = null;
anywheresoftware.b4a.objects.collections.List _result = null;
int _i = 0;
b4a.diplomna.types._orderedgood _orderedgood = null;
anywheresoftware.b4a.objects.collections.Map _map1 = null;
 //BA.debugLineNum = 172;BA.debugLine="Public Sub SerializeOrderedGoods(jstring As String";
 //BA.debugLineNum = 173;BA.debugLine="Dim JSON As JSONParser";
_json = new anywheresoftware.b4a.objects.collections.JSONParser();
 //BA.debugLineNum = 174;BA.debugLine="Dim list1 As List";
_list1 = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 175;BA.debugLine="Dim result As List";
_result = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 177;BA.debugLine="result.Initialize";
_result.Initialize();
 //BA.debugLineNum = 178;BA.debugLine="JSON.Initialize(jstring)";
_json.Initialize(_jstring);
 //BA.debugLineNum = 179;BA.debugLine="list1 = JSON.NextArray";
_list1 = _json.NextArray();
 //BA.debugLineNum = 181;BA.debugLine="For i = 0 To list1.Size - 1";
{
final int step7 = 1;
final int limit7 = (int) (_list1.getSize()-1);
_i = (int) (0) ;
for (;_i <= limit7 ;_i = _i + step7 ) {
 //BA.debugLineNum = 182;BA.debugLine="Dim OrderedGood As OrderedGood";
_orderedgood = new b4a.diplomna.types._orderedgood();
 //BA.debugLineNum = 183;BA.debugLine="Dim Map1 As Map";
_map1 = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 184;BA.debugLine="OrderedGood.Initialize";
_orderedgood.Initialize();
 //BA.debugLineNum = 186;BA.debugLine="Map1 = list1.Get(i)";
_map1.setObject((anywheresoftware.b4a.objects.collections.Map.MyMap)(_list1.Get(_i)));
 //BA.debugLineNum = 188;BA.debugLine="OrderedGood.OrderID = Map1.Get(\"orderID\")";
_orderedgood.OrderID = (int)(BA.ObjectToNumber(_map1.Get((Object)("orderID"))));
 //BA.debugLineNum = 189;BA.debugLine="OrderedGood.GoodID = Map1.Get(\"goodID\")";
_orderedgood.GoodID = (int)(BA.ObjectToNumber(_map1.Get((Object)("goodID"))));
 //BA.debugLineNum = 190;BA.debugLine="OrderedGood.Order = Null";
_orderedgood.Order = (b4a.diplomna.types._order)(anywheresoftware.b4a.keywords.Common.Null);
 //BA.debugLineNum = 191;BA.debugLine="OrderedGood.Qtty = Map1.Get(\"qtty\")";
_orderedgood.Qtty = (int)(BA.ObjectToNumber(_map1.Get((Object)("qtty"))));
 //BA.debugLineNum = 193;BA.debugLine="result.Add(OrderedGood)";
_result.Add((Object)(_orderedgood));
 }
};
 //BA.debugLineNum = 196;BA.debugLine="Return result";
if (true) return _result;
 //BA.debugLineNum = 197;BA.debugLine="End Sub";
return null;
}
public static b4a.diplomna.types._supplier  _serializesupplier(anywheresoftware.b4a.BA _ba,String _jstring) throws Exception{
anywheresoftware.b4a.objects.collections.JSONParser _json = null;
anywheresoftware.b4a.objects.collections.Map _map1 = null;
b4a.diplomna.types._supplier _supplier = null;
 //BA.debugLineNum = 31;BA.debugLine="Public Sub SerializeSupplier(jstring As String) As";
 //BA.debugLineNum = 32;BA.debugLine="Dim JSON As JSONParser";
_json = new anywheresoftware.b4a.objects.collections.JSONParser();
 //BA.debugLineNum = 33;BA.debugLine="Dim Map1 As Map";
_map1 = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 34;BA.debugLine="Dim supplier As Supplier";
_supplier = new b4a.diplomna.types._supplier();
 //BA.debugLineNum = 35;BA.debugLine="Map1.Initialize";
_map1.Initialize();
 //BA.debugLineNum = 36;BA.debugLine="supplier.Initialize";
_supplier.Initialize();
 //BA.debugLineNum = 38;BA.debugLine="JSON.Initialize(jstring)";
_json.Initialize(_jstring);
 //BA.debugLineNum = 39;BA.debugLine="Map1 = JSON.NextObject";
_map1 = _json.NextObject();
 //BA.debugLineNum = 41;BA.debugLine="supplier.ID =  Map1.Get(\"id\")";
_supplier.ID = (int)(BA.ObjectToNumber(_map1.Get((Object)("id"))));
 //BA.debugLineNum = 42;BA.debugLine="supplier.SupplierName =  Map1.Get(\"supplierName\")";
_supplier.SupplierName = BA.ObjectToString(_map1.Get((Object)("supplierName")));
 //BA.debugLineNum = 43;BA.debugLine="supplier.SupploerPhone =  Map1.Get(\"supplierPhone";
_supplier.SupploerPhone = BA.ObjectToString(_map1.Get((Object)("supplierPhone")));
 //BA.debugLineNum = 45;BA.debugLine="Return supplier";
if (true) return _supplier;
 //BA.debugLineNum = 46;BA.debugLine="End Sub";
return null;
}
}
